In [ ]:
#Denisse Maria Ramirez Colmenero - A01561497
#Ejercicios realizados en Modulo 5 - Working with Numpy Arrays & Simple APIs
#Subtema: Numpy 2D Arrays

In [2]:
import numpy as np
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
A 

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [3]:
A.ndim #numero de axis o dimensiones 

2

In [4]:
A.shape #rows x columns, devuelve un tuple 

(3, 3)

In [5]:
A.size #multiplicando rows x columns 

9

In [11]:
#Para index A[rows][columns]
A = [[11,12,13],[21,22,23],[31,32,33]]
A[1][2]

23

In [16]:
x = np.array([[1,0],[0,1]])#multiplicar matrices 
y = np.array([[2,1],[1,2]])
z=x+y
z

array([[3, 1],
       [1, 3]])

In [17]:
#multiplicar matrices por constantes 
y = np.array([[2,1],[1,2]])
z=2*y
z

array([[4, 2],
       [2, 4]])

In [18]:
#hadamart product 
x = np.array([[1,0],[0,1]])
y = np.array([[2,1],[1,2]])
z = y*x
z

array([[2, 0],
       [0, 2]])

In [19]:
#multiplicacion de matrices, las rows de uno deben ser la misma cantidad que las columnas de la otra 
A = np.array([[0,1,1], [1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])
C = np.dot(A,B)
C

array([[0, 2],
       [0, 2]])

In [20]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])